"""
UMAA SA Data Model — convenience re-export shim for RTI Connext DDS 7.7.0
==========================================================================

The canonical UMAA Python types are auto-generated by rtiddsgen 4.6.0 and
live in the ``rtiumaapy`` package:
    /Users/pschmitt/Documents/GitHub/rticonnextdds-usecases-umaa/python

This module re-exports everything an application needs so that imports stay
clean:

    from umaa_types import (
        SpeedReportType, SpeedReportTypeTopic,
        GlobalPoseReportType, GlobalPoseReportTypeTopic,
        UMAA, GUIDUtil, set_timestamp,
    )

rtiumaapy version : 0.1.0
rti.connext version: 7.7.0  (rtiddsgen 4.6.0)
"""

# Pull in both top-level DDS types (and the shared UMAA namespace object)
from rtiumaapy.datamodel.SpeedReportType import (          # noqa: F401,F403
    UMAA_SA_SpeedStatus_SpeedReportType        as SpeedReportType,
    UMAA_SA_SpeedStatus_SpeedReportTypeTopic   as SpeedReportTypeTopic,
    UMAA,
)
from rtiumaapy.datamodel.GlobalPoseReportType import (     # noqa: F401,F403
    UMAA_SA_GlobalPoseStatus_GlobalPoseReportType       as GlobalPoseReportType,
    UMAA_SA_GlobalPoseStatus_GlobalPoseReportTypeTopic  as GlobalPoseReportTypeTopic,
)

# UMAA helper utilities
from rtiumaapy import GUIDUtil, set_timestamp              # noqa: F401

# Commonly-used nested types aliased for convenience
NavigationSolutionEnumType = (
    UMAA.Common.MaritimeEnumeration
        .NavigationSolutionEnumModule
        .NavigationSolutionEnumType
)

VehicleSpeedModeEnumType = (
    UMAA.Common.MaritimeEnumeration
        .VehicleSpeedModeEnumModule
        .VehicleSpeedModeEnumType
)

DateTime           = UMAA.Common.Measurement.DateTime
GeoPosition2D      = UMAA.Common.Measurement.GeoPosition2D
IdentifierType     = UMAA.Common.IdentifierType

Orientation3DNEDType = UMAA.Common.Orientation.Orientation3DNEDType
PitchYNEDType        = UMAA.Common.Orientation.PitchYNEDType
RollXNEDType         = UMAA.Common.Orientation.RollXNEDType
YawZNEDType          = UMAA.Common.Orientation.YawZNEDType
